[build-system]
requires = [
  "setuptools>=18.0",
  "wheel",
  "cython",
  'numpy<1.20.0; python_version<"3.7"',
  'numpy; python_version>="3.7"',
  "torch",
]
build-backend = "setuptools.build_meta"
